name: 🚀 Feature
description: "Submit a proposal for a new feature"
title: "🚀 Feature: "
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out our feature request form
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "🔖 Feature description"
      description: "A clear and concise description of what the feature is."
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: " Have you checked if this issue has been raised before?"
      options:
        - label: "I checked and didn't find similar issue"
          required: True
