---
name: Build packages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created
jobs:
  linux:
    name: Build Packages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Flutter
        run: |
          sudo snap install flutter --classic
          flutter config --enable-linux-desktop
          flutter upgrade
          yes | flutter doctor --android-licenses
          flutter doctor -v
      - name: run `flutter build linux`
        run: flutter build linux --verbose
      - name: Store build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sunflower-dash-linux
          path: build/linux/x64/release/bundle

  snap:
    name: Build snap
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install snapcraft
        run: |
          set -x
          sudo snap install snapcraft --classic
          sudo snap install multipass
          sudo usermod --append --groups lxd ${USER}
          echo /snap/bin >> ${GITHUB_PATH}
          sudo chown root:root /
          sudo /snap/bin/lxd init --auto
      - name: Build snap
        run: sudo snapcraft --use-lxd
