---
name: Jekyll site CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build online documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the site in the jekyll/builder container
        run: |
          chmod -R 777 /srv/jekyll
          docker run \
            --volume ${{ github.workspace }}/docs:/srv/jekyll \
            --volume ${{ github.workspace }}/docs/_site:/srv/jekyll/_site \
            jekyll/jekyll:latest \
            jekyll build
      - name: Store webpage
        uses: actions/upload-artifact@v2
        with:
          name: sunflower-dash-docs
          path: docs/_site
